name: plexus-run
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10,<3.14
  - blast>=2.17.0
  - bcftools>=1.23
  - pip
  - pip:
      - loguru
      - pandas
      - primer3-py>=2.3.0
      - pydantic
      - pysam>=0.23.3
      - rich
      - typer
