# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the entire repository into the container
COPY . .

# Install the package in editable mode
RUN pip install --no-cache-dir -e .

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements-dev.txt

# Command to run your application
CMD ["python", "your_module/main.py"]
